cmd/kubedog/main.go, pkg/kubedog/common.go, pkg/kubedog/job.go, pkg/kubedog/pod.go, pkg/monitor/feed_proto.go, pkg/monitor/job.go, pkg/monitor/pod.go
* Pod Added feed callback.
* Handle Pod resource deletion during watch.
* WaitPod -> WaitPodTillDone.
* chan bool -> chan struct{}.
=> Improve pod and job trackers

pkg/kubedog/deployment.go, pkg/monitor/deployment.go
- feed api
- more debug messages
=> Watch deployment: add replicaset events, add pod events and monitors

pkg/tracker/deployment.go, pkg/tracker/deployment_debug.go, pkg/trackers/rollout/deployment.go, pkg/utils/deployment_utils.go
- return immediately if added deployment is in complete state
- move methods borrowed from k8s/.../controller/utils to utils
- move rich info methods to deployment_debug
- DeploymentFeed.Added receives `completed` argument
=> Handling of initial complete state for rollout mode

pkg/tracker/deployment.go, pkg/tracker/feed_proto.go, pkg/tracker/job.go, pkg/tracker/pod.go, pkg/trackers/follow/pod.go, pkg/trackers/rollout/pod.go
Fixup `rollout.TrackPod` to stop watch when pod is ready.
=> Add pod readyness feed callback

pkg/tracker/deployment.go, pkg/tracker/feed_proto.go, pkg/trackers/follow/deployment.go, pkg/trackers/rollout/deployment.go
- rename complete to ready
- make DeploymentFeedStubImpl ad-hoc implementation
=> Add replicaSet name to AddedPod event

pkg/tracker/common.go, pkg/tracker/deployment.go, pkg/tracker/feed_proto.go, pkg/tracker/job.go, pkg/trackers/follow/deployment.go, pkg/trackers/rollout/deployment.go, pkg/trackers/rollout/job.go, pkg/trackers/rollout/pod.go, pkg/utils/pod_utils.go
Appended IsNew ReplicaSet state to all Deployment events:
- added ReplicaSet
- added Pod
- Pod error
- Pod log chunk
=> Fixed new/current ReplicaSet determination algorithm

cmd/kubedog/main.go, pkg/tracker/daemonset.go, pkg/tracker/daemonset_debug.go, pkg/tracker/deployment.go, pkg/tracker/feed_proto.go, pkg/tracker/replicaset_informer.go, pkg/tracker/statefulset_debug.go, pkg/trackers/follow/daemonset.go, pkg/trackers/rollout/daemonset.go, pkg/trackers/rollout/statefulset.go
- fix exit on resource ready in rollout track mode
- change trackers output to less verbose like stern
=> DaemonSet tracker

.gitignore, README.md, go-release-build.sh
+ Added script to build binaries for the release.
=> Uploaded prebuilt kubedog binaries

pkg/tracker/job.go, pkg/tracker/pod.go
Should fix problems like:
```
deploy/tiller-deploy error: pods "tiller-deploy-7cb58674c6-jb6z8helo" not found
```
=> Do not make direct Get requests for resource manifests for Pod and Job

pkg/tracker/daemonset.go, pkg/tracker/deployment.go, pkg/tracker/job.go, pkg/tracker/pod.go, pkg/tracker/pod_informer.go, pkg/tracker/replicaset_informer.go, pkg/utils/deployment_utils.go
kubernetes.Interface methods changed:
* Core -> CoreV1
* Extensions -> ExtensionsV1Beta1
* Batch -> BatchV1
=> Fix build with latest kubernetes client-go

pkg/tracker/deployment.go, pkg/tracker/rollout_status.go, pkg/tracker/statefulset.go, pkg/tracker/statefulset_debug.go, pkg/utils/deployment_utils.go
- support for partition: 0, no hang in this situation
- support for automatic actions in case of OnDelete, no error
- debug messages for sts are more clearer
- final status works in debug mode
=> fix: rollout track for sts hangs in particular situations

cmd/kubedog/main.go, pkg/kube/kube.go, pkg/utils/file.go
=> feat: kube-context and kube-config flags

pkg/tracker/daemonset/tracker.go, pkg/tracker/deployment/tracker.go, pkg/tracker/job/tracker.go, pkg/tracker/statefulset/tracker.go
```
goroutine 453 [running]:
runtime.throw(0x2b3e301, 0x26)
/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc0007566b8 sp=0xc000756688 pc=0xea72e2
runtime.mapiternext(0xc0007567d8)
/usr/local/go/src/runtime/map.go:790 +0x525 fp=0xc000756740 sp=0xc0007566b8 pc=0xe8a7a5
runtime.mapiterinit(0x27e46c0, 0xc0009979e0, 0xc0007567d8)
/usr/local/go/src/runtime/map.go:780 +0x1c4 fp=0xc000756760 sp=0xc000756740 pc=0xe8a184
github.com/flant/kubedog/pkg/tracker/deployment.NewDeploymentStatus(0x2, 0x600000006, 0x600000006, 0x0, 0xc0007c9880, 0x2, 0x2, 0x0, 0xc0009979e0, 0x0, ...)
/home/distorhead/go/pkg/mod/github.com/flant/kubedog@v0.1.1-0.20190414170322-0b964109a3d7/pkg/tracker/deployment/tracker.go:36 +0x106 fp=0xc0007569c8 sp=0xc000756760 pc=0x2531576 …
```
=> Fix 'concurrent map iteration and map write'

pkg/kube/kube.go
closes https://github.com/flant/werf/issues/1503
=> [client] Enable gcp plugin

pkg/trackers/rollout/multitrack/daemonset.go, pkg/trackers/rollout/multitrack/deployment.go, pkg/trackers/rollout/multitrack/job.go, pkg/trackers/rollout/multitrack/multitrack.go, pkg/trackers/rollout/multitrack/pod.go, pkg/trackers/rollout/multitrack/statefulset.go
* SkipLogsForContainers
* ShowLogsOnlyForContainers
* LogWatchRegexByContainerName
* LogWatchRegex
=> [multitrack] Container log display options

pkg/tracker/daemonset/status.go, pkg/tracker/daemonset/tracker.go, pkg/tracker/deployment/status.go, pkg/tracker/deployment/tracker.go, pkg/tracker/indicators/indicators.go, pkg/tracker/statefulset/status.go, pkg/tracker/statefulset/tracker.go, pkg/trackers/rollout/multitrack/multitrack.go
* Separate table per resource kind.
* Fake waiting-for messages.
* Improved StatefulSet tracker: fix bugs for RollingUpdate strategy, add support for OnDelete strategy.
=> New table format and trackers improvements

pkg/trackers/rollout/multitrack/multitrack_display.go
* Add line between log chunks
* Common column sizes for all resources
* Union "SUCCEEDED", "FAILED" fields for JOB
* Reject AGE collumn for all resources
=> [logging] Improve status progress and log chunks view

cmd/kubedog/main.go, go.mod
=> Suppress k8s.io/klog INFO and WARNING streams

README.md
Doesn't compile as it is - this should fix it :)
=> Fix custom-tracker example in README.md

pkg/tracker/indicators/indicators.go, pkg/tracker/job/status.go, pkg/tracker/pod/status.go
=> Fix job backoff limit; fix Pod status indicator: show red Error pod status

pkg/tracker/daemonset/tracker.go, pkg/tracker/deployment/tracker.go, pkg/tracker/job/tracker.go, pkg/tracker/pod/tracker.go, pkg/tracker/statefulset/tracker.go
Fix Job tracker hangs when BackoffLimitExceeded have occured.
=> Fix pod status handling: handle controller state when controller pod status has been received

cmd/kubedog/main.go, pkg/kube/kube.go
- KubeConfigDataBase64 connection init param support.
- Added KubeConfigOptions struct and renamed config initialization params.
=> Added GetKubeConfig function to initialize custom kube connection and refactor

cmd/kubedog/main.go, go.mod, go.sum, pkg/tracker/indicators/indicators.go, pkg/trackers/elimination/elimination.go, pkg/trackers/rollout/multitrack/multitrack_display.go, pkg/utils/color.go, pkg/utils/table.go, playground/table/main.go
- Up to logboek v0.5.0
- [logging] Explicit use of the default logboek logger
- Don't use formatting functions unnecessarily (LogF -> Log)
=> [logging] logboek v0.5.0

README.md
Update links to binaries in the README
=> [docs] Update install links

pkg/tracker/pod/tracker.go
Remove map shared by multiple goroutines, use channel to pass container state from the parent routing to the child routines instead.
Fixes https://github.com/werf/kubedog/issues/183
=> Fix pod tracker panic

pkg/tracker/deployment/tracker.go
This reverts commit 7a7653d33d7af6e41b0806a48ac6e93862758458.
=> Revert "[debug] Catch tracker exited without resource status resolution bug"

.gitignore, pkg/tracker/canary/tracker.go, pkg/tracker/daemonset/tracker.go, pkg/tracker/deployment/tracker.go, pkg/tracker/event/informer.go, pkg/tracker/job/tracker.go, pkg/tracker/pod/feed.go, pkg/tracker/pod/probes.go, pkg/tracker/pod/status.go, pkg/tracker/pod/tracker.go, pkg/tracker/statefulset/tracker.go, pkg/tracker/tracker.go, pkg/trackers/rollout/multitrack/multitrack.go
=> feat(probes): failure handling for startup/readiness/liveness

scripts/ci/build_release.sh
=> build: add arm64

scripts/ci/build_release_v2.sh
Use bin dir in trdl release structure.
=> infra: fix release build script for trdl

.github/workflows/release_please.yml, README.md
=> ci: add release message footer with installation instructions

pkg/trackers/elimination/elimination.go
Signed-off-by: Timofey Kirillov <timofey.kirillov@flant.com>
=> chore: fix lint problems

pkg/kube/kube.go, pkg/kube/kube_config_getter.go
Signed-off-by: Timofey Kirillov <timofey.kirillov@flant.com>
=> fix: backport pkg/kube package from main for werf v1.1

pkg/kube/kube.go, pkg/kube/kube_config_getter.go
Signed-off-by: Timofey Kirillov <timofey.kirillov@flant.com>
=> fix(kube-client): support kube config merge list option for KubeClientGetter

Makefile, cmd/kubedog/main.go, go.mod, pkg/kube/kube.go, pkg/tracker/generic/common.go, pkg/tracker/generic/event_status.go, pkg/tracker/generic/feed.go, pkg/tracker/generic/ready_condition.go, pkg/tracker/generic/resource_events_watcher.go, pkg/tracker/generic/resource_state_json_paths.go, pkg/tracker/generic/resource_state_watcher.go, pkg/tracker/generic/resource_status.go, pkg/tracker/generic/tracker.go, pkg/tracker/indicators/indicators.go, pkg/tracker/resid/resource_id.go, pkg/tracker/tracker.go, pkg/trackers/rollout/multitrack/canary.go, pkg/trackers/rollout/multitrack/daemonset.go, pkg/trackers/rollout/multitrack/deployment.go, pkg/trackers/rollout/multitrack/generic.go, pkg/trackers/rollout/multitrack/generic/context.go, pkg/trackers/rollout/multitrack/generic/resource.go, pkg/trackers/rollout/multitrack/generic/spec.go, pkg/trackers/rollout/multitrack/generic/state.go, pkg/trackers/rollout/multitrack/job.go, pkg/trackers/rollout/multitrack/multitrack.go, pkg/trackers/rollout/multitrack/multitrack_display.go, pkg/trackers/rollout/multitrack/statefulset.go, pkg/utils/events.go, pkg/utils/json.go
=> feat: generic resources tracking

doc/usage.md
=> docs: generic tracker

pkg/trackers/rollout/multitrack/multitrack_display.go
=> feat: show Ready resources only once

pkg/tracker/indicators/indicators.go, pkg/tracker/resid/resource_id.go, pkg/trackers/rollout/multitrack/multitrack_display.go
=> feat: improved Generic progress status

pkg/tracker/generic/tracker.go
=> fix: reword no activity error message

pkg/tracker/generic/resource_events_watcher.go, pkg/tracker/generic/resource_state_watcher.go
=> fix(generic-tracker): improve logging + few possible fixes 

pkg/tracker/generic/common.go, pkg/tracker/generic/resource_events_watcher.go, pkg/tracker/generic/resource_state_watcher.go, pkg/tracker/generic/resource_status.go, pkg/tracker/generic/tracker.go
=> fix(generic): add logging and don't retry fatal errors on List/Watch

pkg/tracker/generic/common.go, pkg/trackers/rollout/multitrack/multitrack_display.go
=> chore: fix linter issues

pkg/utils/json.go
=> fix(generic): ignore jsonpath errs on Condition search

pkg/tracker/deployment/tracker.go
=> fix: tracking old deployment pods as new
